# Dockerfile.test
FROM node:16-alpine AS build

WORKDIR /project/frontend

COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./

RUN npm install 
COPY ../frontend ./
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /project/frontend/dist  /usr/share/nginx/html