FROM node:16-alpine AS build
WORKDIR /project/frontend
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /project/frontend/dist  /usr/share/nginx/html