FROM node:16-alpine as build
WORKDIR /project/frontend

COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./

RUN npm install --legacy-peer-deps
COPY . .
RUN npm test
RUN npm run build

FROM nginx
EXPOSE 80
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /project/frontend/dist  /usr/share/nginx/html