version: "3"
services:

  backend:
    build: 
      dockerfile: Dockerfile.it
      context: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports: 
      - "8080:8080"  
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    stdin_open: true
    container_name: frontend
    ports: 
      - "3000:3000"    
  mysql:
    image: kimyong120413/mysql:test2
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    restart: unless-stopped
    container_name: mysql
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    links:
      - frontend
      - backend    
