version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /project/frontend/node_modules
      - ./frontend:/project/frontend
    stdin_open: true
    container_name: frontend
    ports: 
      - "3000:3000"
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    links:
      - frontend
      - backend  
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports: 
      - "8080:8080"  
  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - "./mysql/mysql_data:/var/lib/mysql"
      - "./mysql/dev.sql:/docker-entrypoint-initdb.d/dev.sql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapp
