version: "3"
services:

  backend:
    build: 
      dockerfile: Dockerfile.deploy
      context: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports: 
      - "8080:8080"  
  frontend:
    build:
      dockerfile: Dockerfile.deploy
      context: ./frontend
    stdin_open: true
    container_name: frontend
    ports: 
      - "3000:3000" 
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    container_name: nginx    
