# Stage 1: Build the application
FROM maven:latest AS build

WORKDIR /project/backend

RUN apt-get update && \
    apt-get install -y libfreetype6-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy pom.xml and install dependencies
COPY pom.xml .

# Copy source files
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

COPY --from=build /project/backend/target/*.jar app.jar
# Run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]
