
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /project/backend

# Copy the pom.xml and install dependencies
COPY pom.xml .
COPY src ./src

# Package the application
RUN mvn clean package -DskipTests


# 2. Stage 2: Run the application
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /project/backend

# Copy the built JAR file from the build stage
COPY --from=build /project/backend/target/*.jar app.jar
COPY src/main/webapp/WEB-INF/lib/simplecaptcha-1.2.1.jar /project/backend/src/main/webapp/WEB-INF/lib/

# Start the application
ENTRYPOINT ["java", "-jar", "app.jar"]