version: "3"
services:
  backend:
    build: 
      dockerfile: Dockerfile.commit
      context: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports: 
      - "8080:8080"  
    environment:
      SPRING_PROFILES_ACTIVE: commit  
  mysql: 
    image: kimyong120413/mysql-feature:latest
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapp
