name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and start services
        run: |
          docker-compose -f ./docker-compose.yml up -d --build

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if docker exec mysql mysqladmin ping -h "localhost" --silent; then
              break
            fi
            sleep 5
          done

      - name: Run backend tests
        run: |
          docker exec backend mvn test
