name: CI-unit

on:
  push:
    branches:
      - feature/backend/**

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false  # 클린 비활성화
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
             docker build -f ./backend/Dockerfile.unit -t backendunit ./backend  


      - name: Run Unit Tests
        run: |
          docker run backendunit