name: CI

on:
  push:
    branches:
      - feature/backend/**

jobs:
  build:
    runs-on: ubuntu-latest

   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false  # 클린 비활성화

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에 Docker Hub 사용자명 저장
            password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에 Docker Hub 비밀번호 저장
  
      - name: Pull Docker image from Docker Hub
        run: |
            docker pull myusername/my-backend-image:latest  # Docker Hub에서 이미지 가져오기
  
      - name: Run Docker container
        run: |
            docker compose -f docker-compose-backe-feature.yml up 
