name: CI-it

on:
  push:
    branches:
      - feature/backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    

    steps:

      
     

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run mysql
        run: |
           docker compose -f docker-compose-it.yml up -d mysql

      - name: Wait for MySQL
        run: |
          sleep 10  # 적절한 대기 시간 설정

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          while ! mysqladmin ping -h mysql -P 3306 --silent; do
            sleep 1
          done


      - name: Build and Integration test Backend
        run: |
             docker compose -f docker-compose-it.yml up -d backend
    
     
    
