name: CI

on:
  push:
    branches:
      - feature/backend/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f ./backend/Dockerfile.commit -t backendunit ./backend

    - name: Run unit tests
      run: |
        # Start the container in detached mode
        docker run -d --name backendapp backendunit
          
        # Wait for a few seconds to ensure the application is fully started
        sleep 10
          
        # Run the unit tests using the Maven wrapper in the running container
        docker exec backendapp ./mvnw test

        # Stop the container after tests are done
        docker stop backendapp

