name: CI-it

on:
  push:
    branches:
      - feature/backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    

    steps:

      
     

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run mysql
        run: |
           docker compose -f docker-compose-it.yml up -d mysql

      - name: Wait for MySQL
        run: |
          sleep 10  # 적절한 대기 시간 설정

      - name: Build Backend
        run: |
             docker compose -f docker-compose-it.yml up -d backend   

      - name: Run Integrate TEST
        run: |
          docker exec backend mvn clean verify

     
    
