name: CI

on:
  push:
    branches:
      - feature/backend/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f ./backend/Dockerfile.commit -t backendunit ./backend

    - name: Run the application
      run: |
        # Run the application in detached mode
        docker run -d --name backendapp backendunit


    - name: Run unit tests
      run: |
        # Run the unit tests using the Maven wrapper in the running container
        docker exec backendapp ./mvnw test

