name: DOCKER HUB IMAGE PUSH TO DEPLOY [CD]

on:
  push:
    branches:
      - release-*  # master 브랜치에 푸시될 때 실행
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: get_branch_name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"  # 현재 브랜치 이름 추출
          echo "Branch name: $BRANCH_NAME"

          # 버전 값 추출 (예: release-0.1.0)
          if [[ $BRANCH_NAME =~ ^release-(.*\..*)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          else
            echo "No version found in branch name."
          fi


      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
         
      #이미지 빌드 
      - name: Backend Image hub push
        run: |
          docker build -f ./backend/Dockerfile.deploy -t kimyong120413/cicdbackend:${{ env.VERSION }} .
          docker push kimyong120413/cicdbackend:${{ env.VERSION }}

      - name: Frontend Image hub push
        run: |
            docker build -f ./frontend/Dockerfile.deploy -t kimyong120413/cicdfrontend:${{ env.VERSION }} .
            docker push kimyong120413/cicdfrontend:${{ env.VERSION }}

      - name: nginx Image hub push
        run: |
            docker build -f ./nginx/Dockerfile -t kimyong120413/cicdnginx:${{ env.VERSION }} .
            docker push kimyong120413/cicdnginx:${{ env.VERSION }}      
  


     
     
